name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

permissions:
  actions: read
  pull-requests: write

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: valgrind
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Comment on PR
        run: gh pr comment "$NUMBER" --body-file ./valgrind/output.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.workflow_run.event.pull_request.number }}
