name: Receive PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Valgrind
        run: |
          sudo apt update
          sudo apt install -y valgrind

      - uses: actions/checkout@v4

      - name: Build
        run: /bin/bash ./build.sh

      - name: Save PR number
        run: |
          mkdir -p ./valgrind
          valgrind --leak-check=yes ./prog > ./valgrind/output.txt

      - uses: actions/upload-artifact@v4
        with:
          name: valgrind
          path: valgrind/