name: Receive PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Valgrind
        run: |
          sudo apt update
          sudo apt install -y valgrind

      - uses: actions/checkout@v4

      - name: Build
        run: /bin/bash ./build.sh

      - name: Save Valgrind output
        run: |
          mkdir outputs
          valgrind --log-file=./outputs/valgrind.txt --leak-check=yes ./prog

      - uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/